### ISSUE TITLE
Upgrade to Xtext 2.23

### ISSUE THREAD

**Issue by ashpak-shaikh** [intuit/graphql-xtext#8]
Xtext has made optimization to the build process and the dependencies.

**Comment by christyjacob4** [comment]
Hi @ashpak-shaikh  What is the scope of this task ?

**Comment by ashpak-shaikh** [comment]
If you are familiar with xtext, I think it could be done within 2 -3 days. If not it might take a while to figure the correct touch points 

The fastest way would be to copy the existing grammar into a new project created using xtext documentation, copy custom validations and tests and that should be it.
